language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
install:
 - "python setup.py install"
 - "pip install pep8==1.4.5 pyflakes==0.7.2"
script:
 - "pep8 --statistics *.py"
 - "pyflakes *.py | grep -v 'basestring\|unicode' && exit 1"
 - "python setup.py test"
