language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -e .
  - pip install flake8==2.1.0 pep8==1.4.6 pyflakes==0.7.3
  - if [[ $(pip --version | python -c 'import sys; line = sys.stdin.read().splitlines()[0]; print(line.split()[1].split(".", 2)[1])') -le 4 ]]; then pip install -I virtualenv==1.10.1; fi
script:
  - flake8 --statistics *.py
  - python tests.py
matrix:
  allow_failures:
    - python: pypy
